name: Debug-XML

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch XML
        run: |
          curl -L \
            --fail \
            --silent \
            --show-error \
            "https://philsci-archive.pitt.edu/cgi/latest_tool?output=RSS2" \
            -o philsciarchive.xml

      - name: Upload XML artifact
        uses: actions/upload-artifact@v4
        with:
          name: philsciarchive-feed
          path: philsciarchive.xml
